version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  vllm:
    image: vllm/vllm-openai:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Supply a Hugging Face token if the model requires gated access.
      HF_TOKEN: ${HF_TOKEN:-}
    command:
      - "--model"
      - "meta-llama/Llama-3.1-8B-Instruct"
      - "--dtype"
      - "float16"
      - "--tensor-parallel-size"
      - "1"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: 1
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
  
  # vllm-embed:
  #   image: vllm/vllm-openai:latest
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: ["gpu"]
  #   restart: unless-stopped
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ~/.cache/huggingface:/root/.cache/huggingface
  #   environment:
  #     - VLLM_USE_XFORMERS=0
  #     - VLLM_LOGGING_LEVEL=INFO
  #   command: >
  #     --model intfloat/e5-base-v2
  #     --dtype auto
  #     --api-key token-anything
  #     --port 8000
  #     --host 0.0.0.0
  #     --max-num-seqs 2048
  #   ipc: host
  #   shm_size: "8gb"

volumes:
  pg_data:
  hf_cache:
